language: swift
matrix:
    include:
        - osx_image: xcode9.3

before_install:
    - brew update
    - brew install carthage
    - carthage bootstrap --no-use-binaries --platform macos

script:
    - xcodebuild -scheme macos-travis -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7' -configuration Debug test | xcpretty -c